Update auto-cherry-pick.yaml

diff --git a/.github/workflows/auto-cherry-pick.yaml b/.github/workflows/auto-cherry-pick.yaml
--- a/.github/workflows/auto-cherry-pick.yaml
+++ b/.github/workflows/auto-cherry-pick.yaml
@@ -12,6 +12,14 @@ on:
     branches:
       - 'release-*'
       - 'main'
+  workflow_dispatch:
+    inputs:
+      prNumber:
+        description: 'pr number'
+        required: true
+      destBranch:
+        description: 'dest branch, if empty, follow the pr label'
+        required: false
 
 jobs:
   cherry_pick:
@@ -30,35 +38,47 @@ jobs:
         run: |
           set -x
           echo "============ print var ======== "
-          echo "try to get PR from commit"
-          COMMIT=` echo "${JSON}" | jq '.event.commits[0].id' | tr -d '"' ` || true
-          if [ -n "${COMMIT}" ]; then
-              PR_NUMBER=`curl -s -H "Accept: application/vnd.github.groot-preview+json"  https://api.github.com/repos/${{ github.repository }}/commits/${COMMIT}/pulls | jq -r '.[].number' `
+          if ${{ github.event_name == 'workflow_dispatch' }}; then
+                PR_NUMBER=${{ github.event.inputs.prNumber }}
           else
-              echo "error, failed to get any commit ID"
+                    grep -Eio "Merge pull request #[0-9]+ " <<< "${JSON}" || true
+                echo "try to get PR from commit"
+                COMMIT=` echo "${JSON}" | jq '.event.commits[0].id' | tr -d '"' ` || true
+                if [ -n "${COMMIT}" ]; then
+                    PR_NUMBER=`curl -s -H "Accept: application/vnd.github.groot-preview+json"  https://api.github.com/repos/${{ github.repository }}/commits/${COMMIT}/pulls | jq -r '.[].number' `
+                else
+                    echo "error, failed to get any commit ID"
+                fi
+                if [ -z "${PR_NUMBER}" ] ; then
+                    PR_NUMBER=` grep -Eio "Merge pull request #[0-9]+ " <<< "${JSON}" | grep -Eo "[0-9]+" | uniq ` || true
+                fi
+                if [ -z "${PR_NUMBER}" ] ; then
+                    echo "error, failed to get PR NUMBER"
+                    exit 1
+                fi
+                #    grep -Ei "https://github.com/.*/commit" <<< "${JSON}"
+                #PR_COMMITS=` grep -Ei "https://github.com/.*/commit" <<< "${JSON}" | awk -F'"' '{print $4}' | uniq -c | awk '{ if ($1 == 1 ) print $2}' | awk -F'/' '{print $NF}' | tr '\n' ' '  `
+                #    grep '"username":'  <<< "${JSON}"
+                #PR_AUTHOR=` grep '"username":' <<< "${JSON}" | awk -F'"' '{print $4}' | sort | uniq  | grep -v "web-flow"  | head -1 | tr -d '\n' `
+                #    [ -n "${PR_AUTHOR}" ] || { echo "no PR_AUTHOR, ignore" ; }
+          #
           fi
-          if [ -z "${PR_NUMBER}" ] ; then
-              PR_NUMBER=` grep -Eio "Merge pull request #[0-9]+ " <<< "${JSON}" | grep -Eo "[0-9]+" | uniq ` || true
-          fi
-          if [ -z "${PR_NUMBER}" ] ; then
-              echo "error, failed to get PR NUMBER"
-              exit 1
-          fi
+          RP_API_BODY=` curl https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER} -s -H "Accept: application/vnd.github.groot-preview+json" `
+          PR_COMMITS=` echo "${RP_API_BODY}" |  jq ' .merge_commit_sha ' | tr -d '"' `
+          PR_AUTHOR=` echo "${RP_API_BODY}" |  jq ' .user.login ' | tr -d '"' `
           PR_URL="https://github.com/${{ github.repository }}/pull/${PR_NUMBER}"
           ACTION_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-              grep '"username":'  <<< "${JSON}"
-          PR_AUTHOR=` grep '"username":'  <<< "${JSON}" | awk -F'"' '{print $4}' | sort | uniq  | grep -v "web-flow"  | head -1 | tr -d '\n' `
-              [ -n "${PR_AUTHOR}" ] || { echo "no PR_AUTHOR, ignore" ; }
-          gh pr view ${PR_NUMBER}
-          PR_LABEL=` gh pr view ${PR_NUMBER} | grep -i "^labels:" | tr ',' ' ' | tr -s ' ' | sed 's/labels://g' `
-              [ -n "${PR_LABEL}" ] || { echo "no PR_LABEL, ignore" ; }
-          PR_TITLE=`gh pr view ${PR_NUMBER} | sed -n '1 p' `
-              [ -n "${PR_TITLE}" ] || { echo "error, no PR_TITLE " ; exit 1 ; }
+          #gh pr view ${PR_NUMBER} || { echo "failed to get pr ${PR_NUMBER}" ; exit 1 ; }
+          #PR_LABEL=` gh pr view ${PR_NUMBER} | grep -i "^labels:" | tr ',' ' ' | tr -s ' ' | sed 's/labels://g' `
+          #    [ -n "${PR_LABEL}" ] || { echo "no PR_LABEL, ignore" ; }
+          PR_LABEL=` echo "${RP_API_BODY}" |  jq ' .labels[].name ' | tr -d '"' | tr '\n' ' ' `
+          #PR_TITLE=`gh pr view ${PR_NUMBER} | sed -n '1 p' `
+          #     [ -n "${PR_TITLE}" ] || { echo "error, no PR_TITLE " ; exit 1 ; }
+          PR_TITLE=` echo "${RP_API_BODY}" |  jq ' .title ' | tr -d '"' `
           #
-              grep -Ei "https://github.com/.*/commit" <<< "${JSON}"
-          PR_COMMITS=` grep -Ei "https://github.com/.*/commit" <<< "${JSON}" | awk -F'"' '{print $4}' | uniq -c | awk '{ if ($1 == 1 ) print $2}' | awk -F'/' '{print $NF}' | tr '\n' ' '  `
-              [ -n "${PR_COMMITS}" ] || { echo "no PR_COMMITS, ignore" ; }
-          #
+          if [ -z "${PR_COMMITS}" ]; then
+              echo "error, failed to get pr commits"
+          fi
           echo "number: ${PR_NUMBER}"
           echo "action url: ${ACTION_URL}"
           echo "PR_COMMITS: ${PR_COMMITS}"
@@ -70,13 +90,17 @@ jobs:
           #
           echo "=============================== get dest branch from labels ======== "
           WANT_MERGE_BRANCH_LIST=""
-          for LABEL in ${PR_LABEL} ; do
-              echo "checking label $LABEL "
-              PREFIX="${{ env.PR_LABEL_PREFIX_CHERRYPICK }}"
-              grep -E "^${PREFIX}" <<< "${LABEL}" &>/dev/null || continue
-              BRANCH_NAME=` sed 's?'"${PREFIX}"'??' <<< "$LABEL" `
-              WANT_MERGE_BRANCH_LIST+=" $BRANCH_NAME "
-          done
+          if ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.destBranch != '' }}; then
+                WANT_MERGE_BRANCH_LIST=${{ github.event.inputs.destBranch }}
+          else
+                for LABEL in ${PR_LABEL} ; do
+                    echo "checking label $LABEL "
+                    PREFIX="${{ env.PR_LABEL_PREFIX_CHERRYPICK }}"
+                    grep -E "^${PREFIX}" <<< "${LABEL}" &>/dev/null || continue
+                    BRANCH_NAME=` sed 's?'"${PREFIX}"'??' <<< "$LABEL" `
+                    WANT_MERGE_BRANCH_LIST+=" $BRANCH_NAME "
+                done
+          fi
           [ -z "$WANT_MERGE_BRANCH_LIST" ] && echo "no branch to cherry pick" && exit 0
           echo "cherry pick to $WANT_MERGE_BRANCH_LIST "
           #
@@ -120,7 +144,7 @@ jobs:
               PR_BRANCH=robot/cherrypick/pr${PR_NUMBER}/${BRANCH}
               git checkout -b ${PR_BRANCH}
               git branch --show-current
-              FAIL=false 
+              FAIL=false
               UPDATE=false
               ERROR_MESSAGE=""
               for COMMIT in $PR_COMMITS; do
@@ -138,14 +162,14 @@ jobs:
                               continue
                           else
                               FAIL=true
-                              echo "error, failed to cherry pick $COMMIT " 
+                              echo "error, failed to cherry pick $COMMIT "
                               git cherry-pick --abort || true
                               git reset --hard HEAD || true
                               break
                           fi
                     else
                         UPDATE=true
-                        echo "succeed to cherry pick $COMMIT to branch $BRANCH " 
+                        echo "succeed to cherry pick $COMMIT to branch $BRANCH "
                     fi
               done
               if [ "$FAIL" == "true" ] ; then
@@ -161,7 +185,7 @@ jobs:
               if [ "$UPDATE" == "true" ] ; then
                   echo "succeeded to cherry pick to branch $BRANCH "
                   # create a pr
-                  git push origin ${PR_BRANCH}:${PR_BRANCH} -f 
+                  git push origin ${PR_BRANCH}:${PR_BRANCH} -f
                   gh pr create --title "${PR_TITLE}" \
                       --assignee "${PR_AUTHOR},${{ env.DEFAULT_REVIEWER }}" \
                       --label ${{ env.CHERRYPICK_LABEL }} \
