Fix release-v0.1 documentation site bug
Signed-off-by: tao.yang <tao.yang@daocloud.io>

diff --git a/.github/workflows/call-release-pages.yaml b/.github/workflows/call-release-pages.yaml
--- a/.github/workflows/call-release-pages.yaml
+++ b/.github/workflows/call-release-pages.yaml
@@ -4,7 +4,6 @@ env:
   MERGE_BRANCH: github_pages
   PR_LABEL: pr/robot_update
   PR_REVIWER: weizhoublue
-  CHART_OUTPUT_PATH: output/chart/*
 
 on:
   workflow_call:
@@ -12,10 +11,6 @@ on:
       ref:
         required: true
         type: string
-    outputs:
-      artifact:
-        description: "name of chart artifact"
-        value: chart_package_artifact
   # --- call by manual
   workflow_dispatch:
     inputs:
@@ -32,18 +27,19 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       ref: ${{ env.RUN_REF }}
+      skip_all_job: ${{ env.SKIP_ALL_JOB }}
     steps:
       - name: Get Ref
         id: get_ref
         run: |
           pwd
           ls
-          if ${{ inputs.ref != '' }}; then
-              echo "call by workflow_call"
-              echo "RUN_REF=${{ inputs.ref }}" >> $GITHUB_ENV
-          elif ${{ github.event_name == 'workflow_dispatch' }} ; then
+          if ${{ github.event_name == 'workflow_dispatch' }}; then
               echo "call by workflow_dispatch"
-              echo "RUN_REF=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
+              echo "REF=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
+          elif ${{ inputs.ref != '' }}; then
+              echo "call by workflow_call"
+              echo "REF=${{ inputs.ref }}" >> $GITHUB_ENV
           else
               echo "unexpected event: ${{ github.event_name }}"
               exit 1
@@ -52,90 +48,110 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v3
         with:
-          ref: ${{ steps.get_ref.outputs.ref }}
+          fetch-depth: 0
+          ref: ${{ env.REF }}
 
-      - name: Build Site and chart
+      - name: Extract Version
+        id: extract
         run: |
-          make build_doc
-          make chart_package
+          if ! grep -E "^[[:space:]]*v[0-9]+.[0-9]+.[0-9]+[[:space:]]*$" VERSION &>/dev/null ; then
+            echo "not a release version, skip generating doc."
+            cat VERSION
+            echo "SKIP_ALL_JOB=true" >> $GITHUB_ENV
+            exit 0
+          fi
+          # for example v0.6.1, the build's documentation version is v0.6
+          docVersion=` cat VERSION  | tr -d ' ' | tr -d '\n' | grep -Eo "v[0-9]+\.[0-9]+" `
+          if [ -n "${docVersion}" ]; then
+              echo "the version intercepted from the branch is: ${docVersion}"
+          else
+              echo "error, failed to get version." && exit 1
+          fi
+          git checkout -f ${{ env.MERGE_BRANCH }}
+          echo "Switch to the branch:${{ env.MERGE_BRANCH }} where the document is located"
+          ls
+          if [ -e "${docVersion}" ]; then
+              echo "doc version:${docVersion} already exists, just update it."
+              echo "SET_LATEST=false" >> $GITHUB_ENV
+          else
+              echo "The doc version:${docVersion} does not exist yet, while generating the doc and set it to latest"
+              echo "SET_LATEST=true" >> $GITHUB_ENV
+          fi
+          echo "the doc version is: ${docVersion}"
+          echo "DOCS_TAG=${docVersion}" >> $GITHUB_ENV
+
+      - name: build doc site
+        id: build_doc
+        if: ${{ env.SKIP_ALL_JOB != 'true' }}
+        run: |
+          git checkout ${{ env.REF }}
+          ls
+          echo "switch to the release version branch ${{ env.REF }}"
+          pip install mkdocs==1.5.2 mike==1.1.2 mkdocs-material==9.2.8
+          git config user.email "robot@example.com"
+          git config user.name "robot"
+          cp ./docs/mkdocs.yml ./
+          if ${{ env.SET_LATEST == 'true' }} ;then
+              echo "generate doc version:${{ env.DOCS_TAG }} and set to latest."
+              mike deploy --rebase -b ${{ env.MERGE_BRANCH }} --update-aliases ${{env.DOCS_TAG }} latest
+              mike set-default -b ${{ env.MERGE_BRANCH }} latest
+          else
+              echo "the version:${{ env.DOCS_TAG }} of the doc does not need to be set to the latest."
+              mike deploy --rebase -b ${{ env.MERGE_BRANCH }} ${{ env.DOCS_TAG }}
+          fi
+          rm -rf ./site
+          rm -rf ./mkdocs.yml
+          git checkout -f  ${{ env.MERGE_BRANCH }}
+          rm -rf ./charts && rm -rf ./index.yaml && rm -rf ./changelogs
+          tar -czvf ./site.tar.gz *
+          ls
+          echo "Automatic release, offline doc site package ready"
+          echo "Push a doc version: ${{ env.DOCS_TAG }} from branch: ${{ env.REF }}, update it to latest: ${{ env.SET_LATEST }} "
 
       - name: Upload Artifact
-        uses: actions/upload-artifact@v3.1.1
+        uses: actions/upload-artifact@v3.1.2
+        if: ${{ env.SKIP_ALL_JOB != 'true' }}
         with:
           name: site_artifact
-          path: output/docs/site.tar.gz
+          path: site.tar.gz
           retention-days: 0
-          if-no-files-found: error
-
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v3.1.1
-        with:
-          name: chart_package_artifact
-          path: ${{ env.CHART_OUTPUT_PATH }}
-          retention-days: 1
           if-no-files-found: error
 
   create_pr:
     name: Create PR
     needs: [package]
+    if: ${{ needs.package.outputs.skip_all_job != 'true' }}
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
         with:
           ref: ${{ env.MERGE_BRANCH }}
+          fetch-depth: 0
 
       ## doc
-      - name: Prepare
-        run: |
-          # prepare directory
-          [ ! -d "docs/charts" ] || mv docs/charts charts
-          rm -rf docs || true
-          mkdir docs
-
       - name: Download Artifact
         uses: actions/download-artifact@v3.0.2
         with:
           name: site_artifact
-          path: docs
 
       - name: Untar Doc
         run: |
-          cd docs
           tar -xzvf site.tar.gz
           rm -f site.tar.gz
 
-      ## chart
-      - name: Install Helm
-        uses: azure/setup-helm@v3.5
-
-      - name: Download Chart Artifact
-        uses: actions/download-artifact@v3.0.2
-        with:
-          name: chart_package_artifact
-          path: charts/
-
-      - name: Update Chart Yaml
-        run: |
-          mv charts docs/charts
-          name=${{ github.repository }}
-          proj=${name#*/}
-          url=https://${{ github.repository_owner }}.github.io/${proj}
-          cd docs
-          helm repo index  ./charts  --url ${url}/charts
-          mv ./charts/index.yaml ./index.yaml
-
-      # https://github.com/peter-evans/create-pull-request
+      # Allow auto-merge on general
       - name: Create Pull Request
         id: create_pr
         uses: peter-evans/create-pull-request@v5.0.2
         with:
-          title: "robot Update doc from ${{ needs.prepare_doc.outputs.ref }} to branch ${{ env.MERGE_BRANCH }} "
-          commit-message: "robot Update chart from ${{ needs.prepare_doc.outputs.ref }} to branch ${{ env.MERGE_BRANCH }} "
+          title: "robot update website from ${{ needs.package.outputs.REF }} to branch ${{ env.MERGE_BRANCH }} "
+          commit-message: "robot update website from  ${{ needs.package.outputs.REF }} to branch ${{ env.MERGE_BRANCH }} "
           branch-suffix: timestamp
           branch: robot/update_doc
           delete-branch: true
           base: ${{ env.MERGE_BRANCH }}
           signoff: true
-          token: ${{ secrets.WELAN_PAT }}
+          token: ${{ secrets.GITHUB_TOKEN }}
           labels: ${{ env.PR_LABEL }}
+          reviewers: ${{ env.PR_REVIWER }}
