ci: lock check (#135)
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/.github/workflows/lint-golang.yaml b/.github/workflows/lint-golang.yaml
--- a/.github/workflows/lint-golang.yaml
+++ b/.github/workflows/lint-golang.yaml
@@ -154,8 +154,8 @@ jobs:
         run: |
           result=${{ steps.golangci_lint.outcome }}
           [ "${result}"x == "failure"x ] && echo "step golangci_lint failed" && exit 1
-          result=${{ steps.other.outcome }}
-          [ "${result}"x == "failure"x ] && echo "step gokart failed" && exit 3
+          result=${{ steps.lintgolang.outcome }}
+          [ "${result}"x == "failure"x ] && echo "step lintgolang failed" && exit 3
           echo "all succeed"
           exit 0
 
